- name: install vscode libs
  shell: apt-get -y install libgtk2.0-0 libgconf-2-4 libnss3 libasound-dev
- name: install vscode
  shell: >
    cd ~/src;
    wget -t 1 https://go.microsoft.com/fwlink/?LinkID=620884 -O vscode.zip;
    unzip vscode.zip;
    ln -s ~/src/VSCode-linux-x64/code /usr/bin/vscode;
    cd ~/;
